metrics:
    server_name: string         # server name
    mount_point: string         # partition mount point '/' or 'C:'
    total_space: number         # partition total space in unit 'TB', 'GB', 'MB', KB, 'B'
    free_space: number          # partition free space in unit 'TB', 'GB', 'MB', KB, 'B'
    unit: string                # unit 'TB', 'GB', 'MB', KB, 'B'

critical:
    when: (server_name == "my_server1" && free_space < 10) || (server_name == "my_server2" && free_space <= 17) # add your condition here
    repeat: 20 # the time in minute wait for send again the notification if the critical condition persist
    email:
        tpl: You have the partition {{name}} with {{free_percent_space}} percent free # the template email send

default: normal